#!/bin/dash
#
# usage:
#
#     audaciousctl -d select dir
#     audaciousctl -f select file
#     audaciousctl -u update file list
#     audaciousctl -l load stored directory
#     audaciousctl [dir] store directory
#
set -e

dir=~/.config/audacious
config="$dir/mp3-home-dir"
stored="$dir/stored"
filelist="$dir/filelist"
tag="$dir/tag"

if [ ! -d ~/$dir ]; then
	echo "creating dir $dir"
	mkdir -p $dir
fi

# remove empty directories from list
not_empty() {
	while read directory
	do
		if [ "$(ls -A "$directory" )" != "" ]; then
			echo "$directory"
		fi
	done
}

select() {
	echo "audacious root dir config file: $config"

	root=$([ -f $config ] && head -n 1 $config || echo "")
	if [ ! -d "$root" ]; then
		echo "mp3 root dir not configured"
		root=$(zenity --entry --text="mp3 root dir not configured in $config, where to load mp3 from?")
		if [ "$root" != "" ]; then
			echo "$root" > $config
			update
		fi
	fi

	if [ "$root" != "" ]; then
		echo "root: $root"
		cd $root
		if [ "$1" = "dir" ]; then
			selection=$(find "$root" -type d | not_empty | cut -c $(($(echo "$root" | wc -m)+1))- | rofi -i -l 40 -dmenu)
		else
			selection=$(cat $filelist | cut -c $(($(echo "$root" | wc -m)+1))- | rofi -i -l 40 -dmenu)
		fi
		if [ "$selection" != "" ]; then
			audacious "$root/$selection"
		fi
	fi
}

load() {
	path="$(cat "$stored")"
	nohup audacious "$path" > /dev/null &
}

store() {
	if [ -f "$1" -o -d "$1" ]; then
		echo "$PWD/$1" > $stored
		load
	else
		echo "invalid argument: '$1'"
	fi
}

update() {
	echo "audacious root dir config file: $config"
	if [ -f $config ]; then
		root=$([ -f $config ] && head -n 1 $config || echo "")
		find "$root" -type f > $filelist
	else
		echo "root not set!"
	fi
}

case "$1" in
	-d) select dir ;;
	-f) select file ;;
	-l) load ;;
	-u) update ;;
	*) store "$1" ;;
esac




