#!/bin/sh
set -e

dir=~/.config/audacious
config=$dir/mp3-home-dir
type=$([ "$1" = "-f" ] && echo "f" || echo "d")
echo "audacious root dir config file: $config"

if [ ! -d ~/$dir ]; then
	echo "creating dir $dir"
	mkdir -p $dir
fi


if [ ! -f $config ]; then
	echo "mp3 root dir not configured"
	root=$(zenity --entry --text="mp3 root dir not configured in $config, where to load mp3 from?")
	if [ "$root" != "" ]; then
		echo "$root" > $config
	fi
fi

# remove empty directories from list
not_empty () {
	while read directory
	do
		if [ "$(ls -A "$directory" )" != "" ]; then
			echo "$directory"
		fi
	done
}

if [ -f $config ]; then
	root=$(head -n 1 $config)
	cd $root
	selection=$(find $root -type $type | not_empty | rofi -i -l 40 -dmenu)
	if [ "$selection" != "" ]; then
		audacious "$selection"
	fi
fi

