#!/bin/sh

if [ ! "$(ls *.img)" ]; then
	echo 'create image of size [100G]:'
	read size
	size=$([ "$size" == "" ] && echo 100G || echo "$size")
	qemu-img create disk.img $size

	if [ -f "$1" -o "$(ls *.iso)" ]; then
		echo "iso found"
	else
		echo "no iso found!"
		echo "either call: autoqemu [iso]"
		echo "or place iso in current directory"
		exit 4
	fi
fi

params="-m 4G -smp 2 -enable-kvm -soundhw hda"

if [ "$1" != "" ]; then
	params="$params -cdrom $1"
fi
for iso in $(ls | grep '[.]iso$')
do
	params="$params -cdrom $iso"
done
for image in *.img
do
	params="$params -drive file=$image,format=raw"
done
if [ -f vga.txt ]; then
	params="$params -vga $(cat vga.txt)"
fi

[ "$1" ] && params="$params -boot d"

echo "qemu-system-x86_64 $params"
qemu-system-x86_64 $params


