#!/bin/dash

lsblk

DEVICES=$(lsblk -l -o NAME | sed '1d;/sd[a-z][0-9]/!d')
MOUNTED=$(cat /proc/mounts | sed "/^\/dev/!d;s: .*::" | sort -u)
FS="vfat ntfs ext4"

if [ "$1" ]
then
	FS="$1"
fi

echo ""
echo "mounted:"
echo "$MOUNTED"

echo ""
for DEVICE in $DEVICES
do
	FULL_INFO=$(udisksctl info -b /dev/$DEVICE)
	UUID=$(echo "$FULL_INFO" | sed '/^[ \t]*IdUUID:/!d; s/.*[ \t]//')
	LABEL=$(echo "$FULL_INFO" | sed '/^[ \t]*IdLabel:/!d; s/.*[ \t]//')
	TYPE=$(echo "$FULL_INFO" | sed '/^[ \t]*IdType:/!d; s/.*[ \t]//')

	for filter in $FS
	do
		if [ "$TYPE" = "$filter" ]
		then
			echo "/dev/$DEVICE $TYPE ($LABEL) => $UUID"
			if [ "$(echo "$MOUNTED" | grep $DEVICE)" != "" ]
			then
				echo "already mounted"
			else
				udisksctl mount -b "/dev/$DEVICE"
			fi
			echo ""
		fi
	done
done



