#!/bin/dash
set -e

JAR_REMOTE='https://search.maven.org/remotecontent?filepath=org/mozilla/rhino/1.7.14/rhino-1.7.14.jar'
JAR_LOCAL=~/.cache/rhino.jar
JS_REMOTE='https://github.com/CSSLint/csslint/raw/master/dist/csslint-rhino.js'
JS_LOCAL=~/.cache/csslint.js

wgetc "$JAR_REMOTE" "$JAR_LOCAL"
wgetc "$JS_REMOTE" "$JS_LOCAL"

set -x
java -jar "$JAR_LOCAL" "$JS_LOCAL" "$@"

