#!/bin/dash
set -e

yesterday=$(date -d yesterday '+%Y-%m-%d')
today=$(date '+%Y-%m-%d')
tomorrow=$(date -d tomorrow '+%Y-%m-%d')

config=~/.config/daily/config.txt
backup=~/.config/daily/backup/$today.txt
parsed=`getopt "adtv" "$@"` || usage

PLAIN='\033[0m'
YELLOW='\033[1;33m'
RED='\033[1;31m'




usage() {
	all | head -n 5
	echo
	echo usage: `basename $0` -[at] 1>&2
	echo `basename $0` -a    list config 1>&2
	echo `basename $0` -d    delete today 1>&2
	echo `basename $0` -t    show today 1>&2
	echo `basename $0` -v    edit in vim 1>&2
	exit 0
}

delete() {
	sed -i "0,/$today/d;/$today/d" $config
	today
}

today() {
	sort $config | sed '/^$/d' > $backup
	if grep -q "$yesterday" $backup; then
		sed -i "0,/$yesterday/d;/$yesterday/d" $backup
		cp $backup $config
	fi

	todmsg=$(sed -n "/$today/p" $config)
	if [ "$todmsg" != "" ]; then
		echo "$RED$todmsg$PLAIN"
	fi

	tommsg=$(sed -n "/$tomorrow/p" $config)
	if [ "$tommsg" != "" ]; then
		echo "$YELLOW$tommsg$PLAIN"
	fi
}

all() {
	sort $config | sed '/^$/d'
}

edit() {
	vim $config
}



if [ ! -f "$config" ]; then
	echo $RED"file does not exist: $config $PLAIN"
	exit 44
fi

set -- $parsed

case "$1" in
	-a) all; break;;
	-d) delete; break;;
	-t) today; break;;
	-v) edit; break;;
	*) usage;;
esac











