#!/bin/dash

build=/tmp/build/darkdoc/spool
output="$build"/output.html
css=$IBIN/data/darkdoc/style.css
endpoint=http://localhost:8000/web/push/body

update() {
	if [ ! -f "$1" ]; then
		echo "*error*: file does not exist: '$1'"
		return
	fi
	asciidoctor "$1" -o "$output"
	if [ -f "$css" ]; then
		curl -s "$endpoint" -X POST -d "<style>$(cat "$css")</style>$(sed '0,/<body/d;/<\/body>/,$d' "$output")"
	else
		echo "*error*: file not found → $css"
	fi
}

document() {
	echo "$1"
	asciidoctor "$1" -o "$output"
	pandoc "$output" -o document.docx
}

stamp() {
	stat -c "%y" "$1"
}

watch() {
	lastcss=""
	lastadoc=""
	while true
	do
		cssstamp=$(stamp "$css")
		adocstamp=$(stamp "$1")
		if [ "$lastadoc" != "$adocstamp" -o "$lastcss" != "$cssstamp" ]; then
			echo "refresh $(date)"
			lastcss="$cssstamp"
			lastadoc="$adocstamp"
			update "$1"
		fi
		sleep 0.1
	done
}

mkdir -p "$build"

if [ "$1" = "" ]; then
	echo "*error*: missing argument document"
elif [ "$1" = "-w" ]; then
	watch "$2"
elif [ "$1" = "-d" ]; then
	document "$2"
else
	update "$1"
fi

