#!/bin/sh
set -e
sh -n $0

config=~/.config/dp
presets=$config/presets
ports=$config/ports
feh=$config/feh-dir


die() {
	echo >&2 "$@"
	exit 1
}

background() {
	echo "image dir config file: $feh"
	root=$([ -f $feh ] && head -n 1 $feh || echo "")
	if [ ! -d "$root" ]; then
		echo "bacground image dir not configured"
		root=$(zenity --entry --text="background image dir not configured in $feh, where to load images from?")
		if [ "$root" != "" ]; then
			echo "$root" > $feh
		fi
	fi
	random=$(find "$root" -type f | sort -R | head -n 1)
	echo "selected image: $random"
	echo "$random" >> /tmp/feh.txt
	feh --bg-fill "$random"
}

apply() {
	xrandr='xrandr'
	previous=""
	for index in $(seq 5)
	do
		setting=$(echo "$1" | cut -c $index)
		port=$(sed -n "${index}p" $ports)

		[ "$port" = "" ] && break
		[ "$setting" = "" ] && break
		[ "$setting" = "." ] && continue

		xrandr="$xrandr --output $port"

		case $setting in
			a)   xrandr="$xrandr --auto";;
			n)   xrandr="$xrandr --auto --rotate normal";;
			l)   xrandr="$xrandr --auto --rotate left";;
			r)   xrandr="$xrandr --auto --rotate right";;
			0)   xrandr="$xrandr --off"; continue;;
			o)   xrandr="$xrandr --off"; continue;;
			=)   xrandr="$xrandr --rotate normal";;
			'[') xrandr="$xrandr --rotate left";;
			']') xrandr="$xrandr --rotate right";;
			*)   die "unknown setting: $setting"
		esac

		[ "$previous" != "" ] && xrandr="$xrandr --right-of $previous"
		previous="$port"

	done
	if grep -q "^l " $presets; then
		sed -i "s/^l .*/l $1/" $presets
	else
		echo "l $1" >> $presets
	fi

	echo "$xrandr" | tee /tmp/dp.log
	$xrandr
	redshift -P -O 4500
	exit 0
}

load() {
	# find matching preset
	while read id settings
	do
		if [ "$1" = "$id" ]; then
			apply $settings
		fi
	done < $presets
	notify-send "preset $1 not found"
}

xrandr | grep ' connected '
echo ""

[ -d $config ] || mkdir $config

if [ "$1" = "-r" ]; then
	rm "${ports:?}"
	shift
fi
if [ ! -f "$ports" ]; then
	info=$(xrandr)
	echo "$info" | sed -n '/ connected /{s/ .*//;p}' > $ports
	echo "$info" | sed -n '/disconnected/{s/ .*//;p}' >> $ports
fi

if [ ! -f $presets ]; then
	echo "0 ooooo" >> $presets
	echo "1 noooo" >> $presets
	echo "2 nnooo" >> $presets
	echo "3 nnnoo" >> $presets
	echo "4 nnnno" >> $presets
	echo "5 nnnnn" >> $presets
	echo "6 loooo" >> $presets
	echo "7 lnooo" >> $presets
	echo "8 lnnoo" >> $presets
	echo "9 lnnno" >> $presets
	echo "h =====" >> $presets
	echo "- onooo" >> $presets
	echo "= nnooo" >> $presets
	echo "l nnnnn" >> $presets
fi

[ "$#" -gt 0 ] || die "either call $0 -p [preset] or $0 [settings]"

if [ "$1" = "-p" ]; then
	load $2
else
	apply $1
fi


