#!/usr/bin/dash

die() {
    echo >&2 "$@"
    exit 1
}

[ "$#" -ge 2 ] || die "usage:\n\teach [find] [cmd]\n\texample: each *.py 'grep -H import'"

files=$(find -name $1)

# echo ""
# echo "search command?"
# echo "grep 'test'"
# echo "sed -n '/test/p'"
# echo ""

# read cmd
cmd=$2

# echo ""
# echo "cmd $cmd"
# echo ""

for file in $files; 
do 
$cmd $file

# echo "$file "
# echo "@@@ $test"
# $test > /tmp/spool.log
# cat /tmp/spool.log
done

