#!/bin/sh
set -e

installer=~/Development/git/installer/includes/eclipse-minimal.sh
executable=~/Applications/eclipse/eclipse
workspaces=~/Development/workspace

open() {
	workspace=$workspaces/$1

	if [ -d "$workspace" ]; then
		echo "eclipse -data $workspace"
		$executable -data $workspace &
	else
		echo "not a directory! $workspace"  
	fi
}

if [ "$1" = "-w" ]; then
	workspace=$(ls ~/Development/workspace | rofi -dmenu -theme purple)
	[ $? ] && open "$workspace"

elif [ "$1" ]; then
	open "$1"
else
	$executable &
fi


