#!/bin/sh
# script to run git commands on multiple git repos simultaneously


YELLOW='\033[1;33m'
RED='\033[1;31m'
PLAIN='\033[0m'


if [ "$1" = "-c" ]; then
	message=$(echo "$@" | sed 's/^-c *//')
	if [ -z "$message" ]; then
		echo "$RED    git commit message required! $PLAIN"
		exit 500
	fi
fi


if [ "$(echo "$1" | cut -c 1)" = "@" ]; then
	set -e
	project=$(echo "$1" | sed 's/@//')
	repo=~/Development/git/$project
	echo "$repo"
	shift

	if [ ! -d $repo ]; then
		echo "$RED repo $project does not exist $PLAIN"
		exit 404
	fi

	cd $repo
	if [ "$1" = "acp" ]; then
		git add --all
		if [ -z "$2" ]; then
			git commit
		else
			git commit -m "$2"
		fi
		git push
		exit 0
	fi

	if [ "$1" = "untracked" ]; then
		for file in $(git status | sed '0,/Untracked.*/d;/\t/!d')
		do
			if [ -f "$file" ]; then
				echo gedit $file
				gedit "$file" &
			else
				find "$file" -type f -exec echo "gedit {}" \;
				find "$file" -type f -exec gedit {} \; &
			fi
		done
		exit 0
	fi

	if [ "$1" = "" ]; then
		git status
	else
		git "$@"
	fi
	exit 0
fi


for dir in $(ls ~/Development/git)
do
	cd ~/Development/git/$dir
	if [ ! -d ".git" ]; then
		continue
	fi

	color=""
	branch=$(git status | sed '/^On branch.*/!d; s/^On branch //')
	untracked=$(git status | sed '/^Untracked.*/!d; s/ntracked.*//')
	changes=$(git status | sed '/^Changes.*/!d; s/hanges.*//')
	
	if [ ! -z "$untracked$changes" ]; then
		color=$YELLOW
	fi
	
	echo "$color[$branch] $dir $untracked$changes$PLAIN"

	
	if [ "$1" = "acp" ]; then
		if [  ! -z "$untracked$changes" ]; then
			git add --all
			git commit -m "$message"
			git push
			echo ''
		fi

	elif [ "$#" -gt 0 ]; then
		git "$@"
		echo
	fi
done

