#!/bin/sh

workspace=$(i3-msg -t get_workspaces | jq '.[] | select(.focused).num')
output=$(i3-msg -t get_workspaces | jq '.[] | select(.focused).output')
windows=$(i3-msg -t get_tree | jq ".nodes[] | select(.name == $output) | .nodes[] | select(.name == \"content\") | .nodes[] | select(.num == $workspace) | .nodes[0].nodes")
ids=$(echo "$windows" | jq '.[] | .id')
count=$(echo "$ids" | wc -l)
focused=$(echo "$windows" | jq '.[] | select(.focused == true) | .id')
index=$(echo "$ids" | grep -n "^$focused$" | sed 's/:.*//')

if [ "$1" = "-r" ]; then
	target=$( [ $index -eq 1 ] && echo $count || echo $(($index-1)) )
else
	target=$(( $index % $count + 1 ))
fi

select=$(echo "$ids" | sed -n "${target}p")
echo "$ids"
echo
echo "original: $focused"
echo "focus: $select"
echo
echo "index: $index"
echo "target: $target"
echo

i3-msg "[con_id=\"$select\"] focus"

