#!/usr/bin/perl
use 5.26.1;

my $file = '~/Applications/links/links.ini';
my $selected = `cat $file | grep name | sed 's/.*=//' | rofi -i -l 40 -dmenu`;
my @lines = `cat $file`;
my $index = 0;
my $browser = @ARGV ? $ARGV[0] : 'firefox';


sub try_link() {
	say;
	my %link = {};

	while ( $index <= $#lines ) {
		my $line = $lines[$index];
		chomp $line;

		if ($line =~ /\s++([^=]++)=(.*+)/) {
			say "regex match: '$1' = '$2'";
			$link{$1} = $2;

		} else {
			last; # next link
		}
		$index++;
	}
	if ($link{'name'} eq $selected) {
		say "";
		say "match:", $link{'name'};
		say "user:", $link{'user'};
		system "echo '$link{'user'}' | xclip";
		system "$browser $link{'url'} &";
		exit 0;
	}
}

sub goto_next_link() {
	while ( $index < $#lines and index($lines[$index], '=') < 0 ) {
		$index++;
	}
}


chomp $selected;
say "selection: '$selected'";
exit 1 if ! $selected;

while ( $index < $#lines ) {
	goto_next_link();
	try_link();
}


