#!/bin/sh
set -e

dir=~/.ssh
config=$dir/bin_proxy
echo "proxy config file: $dir"

if [ ! -d $dir ]; then
	echo "creating dir $dir"
	mkdir $dir
fi


if [ ! -f $config ]; then
	echo "proxy not configured"
	proxy=$(zenity --entry --text="Proxy not configured in $config, please supply [user]@[host]")
	echo "$proxy" > $config
fi

if [ -f $config ]; then
	proxy=$(cat $config)
	gnome-terminal --title="proxy" -- ssh $proxy -D 12345 
fi

