#!/bin/sh
set -e
set -u

output=$(xrandr | grep HDMI | grep -v disconnected)
port=$(echo "$output" | sed 's: .*::')
resolution=$(echo "$output" | sed 's:.*connected ::;s:+.*::')
width=$(echo "$resolution" | sed 's:x.*::')
height=$(echo "$resolution" | sed 's:.*x::')

xrandr --output $port  --rotate ${1-left}

cache=/tmp/snap
if [ -d $cache ]; then
	chmod -R +w $cache
	rm -rf $cache
fi
$IBIN/util/displays

