#!/bin/sh

value=$(zenity --entry)

if [ "$value" = "" ]; then
	exit 0
fi

store() {
	xdotool key $1
	echo -n "$2" | xclip -selection clipboard
	while [ "$2" = $(xclip -o -selection clipboard) ]
	do
		sleep 1
	done
}

case "$value" in
	"'a"|"a'") store Aacute 'á';;
	"'e"|"e'") store Eacute 'é';;
	"'i"|"i'") store Iacute 'í';;
	"'o"|"o'") store Oacute 'ó';;
	'"o'|'o"') store Odiaeresis 'ö';;
	"''o"|"o''") store odoubleacute 'ő';;
	"'u"|"u'") store Uacute 'ú';;
	'"u'|'u"') store Udiaeresis 'ü';;
	"''u"|"u''") store udoubleacute 'ű';;
	*) zenity zenity --info --text="unknown key code";;
esac

