#!/bin/dash

automount
dp -p l &
sed -i -r '/^\s*+(cd|l[sla]( -[la]*)?|gits|history|z)\s*+$/d' ~/.bash_history &
unclutter -idle 1 -root &
setxkbmap -layout erik &
xsetroot -solid "#333" &
for id in $(xinput list | grep -i touchpad | sed -r 's/.*id=([0-9]*).*/\1/'); do xinput --disable $id; done &
rm -rf ~/.lesshst ~/.swt ~/.wget-hsts ~/.xsession-errors.old ~/.sudo_as_admin_successful &
redshift -P -O 4500 &
xset -dpms &
xset s off &
flatpak run org.gajim.Gajim &
nmcli radio wifi off &
sink streamer


