#!/usr/bin/dash

cheat() {
	cd ~/Development/git/cheat/files
	exec vim $(find . -type f -name "*$1*")
}

dependencies() {
	project="$1"
	dir=~/Development/git/$project
	if [ -d $file ]; then
		cd $dir
		exec vim main/config/dependencies.txt
	else
		echo "no project named '$project' exists"
	fi
}

vimhelp() {
	exec vim "+help $1 | only"
}

vimgrep() {
	exec vim $(find -type f | sed '/\/\.git\//d' | grep "$1")
}

vimwhich() {
	file=$(which "$1")
	if [ -f "$file" ]; then
		exec vim "$file"
	else
		echo "cannot find '$1'"
	fi
}

case $1 in
	-c) cheat        "$2";;
	-d) dependencies "$2";;
	-g) vimgrep      "$2";;
	-h) vimhelp      "$2";;
	-w) vimwhich     "$2";;
esac



