#!/bin/dash

die(){
	echo "$@" >&2
	exit 5
}

cheat() {
	cd ~/Development/git/cheat/files
	exec vim $(find . -type f -name "*$1*")
}

dependencies() {
	project="$1"
	dir=~/Development/git/$project
	if [ -d $file ]; then
		cd $dir
		exec vim main/config/dependencies.txt
	else
		echo "no project named '$project' exists"
	fi
}

vimhelp() {
	exec vim "+help $1 | only"
}

vimgrep() {
	exec vim $(find -type f | sed '/\/\.git\//d' | grep "$1")
}

vimproject() {
	[ ! -z "$1" -a ! -z "$2" ] || die "expecting 2 arguments: [project] [file]"
	dir=~/Development/git/$1
	[ -d $dir ] || die "invalid project '$1'"
	cd $dir

	found=/tmp/vim/found.txt
	find -type f | grep -v '/[.]git/' | grep "$2" > $found
	count=$(cat /tmp/vim/found.txt | wc -l)
	cat $found
	echo "$count matches"

	if [ $count -gt 0 -a $count -lt 4 ]; then
		vim $(cat $found)
	fi
}

vimwhich() {
	file=$(which "$1")
	if [ -f "$file" ]; then
		exec vim "$file"
	else
		echo "cannot find '$1'"
	fi
}

case $1 in
	-c) cheat        "$2"      ;;
	-d) dependencies "$2"      ;;
	-g) vimgrep      "$2"      ;;
	-h) vimhelp      "$2"      ;;
	-p) vimproject   "$2" "$3" ;;
	-w) vimwhich     "$2"      ;;
esac



