#!/bin/dash
set -e
log=/tmp/build/vimtastic.log
[ -f "$log" ] && rm "$log"

echo "vimtastic: $@"
# check file extension
file="$1"
ext="${1##*.}"
if [ "$ext" != "java" ]; then
	echo "*error* file extension not supported!"
	exit 1
fi

# get project name for antastic
projectdir=$(echo "$1" | grep -oE '.*/Development/git/[^/]+')
echo "projectdir: '$projectdir'"

project="${projectdir##*/}"
echo "project: $project"

if [ "$project" = "" ]; then
	echo "*error* unable to get project name!"
	exit 2
fi

OLD_IFS="$IFS"
IFS=
antastic "$project" 2>&1 | while read -r line
do
	#echo "$line"

	# ant build files, then javac, then checkstyle
	echo "$line" | sed -nr '/^\//p' >> /tmp/build/vimtastic.log
	echo "$line" | sed -nr '/\s*\[javac\]/{s|^\s*\[javac\] ||;p}' >> /tmp/build/vimtastic.log
	echo "$line" | sed -nr "/\s*\[checkstyle\]/{s|\[checkstyle\] \[ERROR\] ||;s|(:[0-9]+:)[0-9]+:|\1|;p}" >> /tmp/build/vimtastic.log

	#if echo "$line" | grep -q "\[javac\]"; then
		#echo "$line" | sed -r "s/^\[javac\] //" >> /tmp/build/vimtastic.log
	#fi
	#if echo "$line" | grep -q "\[checkstyle\]"; then
		#echo "$line" | sed -r "s/\[checkstyle\] \[ERROR\] //" >> /tmp/build/vimtastic.log
	#fi
	# ant build files
done
IFS="$OLD_IFS"

