#!/bin/dash
# convenience script for running qemu without having to specify a long list of parameters

cache=~/.cache/autoqemu
params="-m 4G -smp 2 -cpu host -enable-kvm -soundhw hda "

while [ "$1" != "" ]
do
	if [ -f "$1" ]; then
		echo "iso found"
		params="$params -cdrom $1 -boot d"
	elif [ -d "$1" ]; then
		dir="$1"
	else
		dir=$(sed -nr "/\/$1$/{p;q}" $cache)
	fi
	shift
done

cd "$dir"
if [ ! "$(ls *.img)" ]; then
	echo 'create image of size [50G]:'
	read size
	size=$([ "$size" = "" ] && echo 50G || echo "$size")
	qemu-img create disk.img $size
fi

if [ ! "$(ls *.img)" ]; then
	exit 44
fi

[ -f "$cache" ] && sed -ir "/\/${PWD##*/}$/d" $cache
echo "$PWD" >> "$cache"
for image in *.img
do
	params="$params -drive file=$image,format=raw"
done
if [ -f params.txt ]; then
	params="$params $(cat params.txt)"
fi

if ! echo "$params" | grep -q -- '-m [0-9]\+G'; then
	params="$params -m 4G"
fi

echo "qemu-system-x86_64 $params"
qemu-system-x86_64 $params


