#!/bin/sh
set -e


die() {
    echo >&2 "$@"
    exit 1
}

parents() {
	mkdir -pv $(dirname "$1")
}


[ "$#" -ge 2 ] || die "2 arguments required: [CACHE_FILE] [URL] [FILE]..."
cache="$1"
url="$2"


if [ ! -f "$cache" ]
then
	parents "$cache"
	wget "$url" -O "$cache"
fi

# delete cached file if it is empty
size=$(wc -c < "$cache")
if [ $size -le 0 ]
then
	rm $cache
	die "downloaded file is empty: '$url'"
fi

shift 2
for file in "$@"
do
	parents "$file"
	cp -v "$cache" "$file"
done







