#!/bin/dash
set -e

download() {
	url="$1"
	[ -d /tmp/dl ] || mkdir /tmp/dl
	name=$(echo "$url" | sed 's|.*[?]||;s|[^=]*=||;s|[&].*||')
	log="/tmp/dl/$name"
	echo "downloading: $1 => log: $log \n"
	nohup youtube-dl "$url" > $log 2> /dev/null &
}

interactive() {
	echo "## interactive ##\n"
	while read line
	do
		if [ "$line" != "" ]; then
			download "$line"
		fi
	done
}

toggle() {
	if [ "$#" -eq 0 ]; then
		interactive
		exit 0
	fi

	while [ "$1" != "" ]
	do
		echo "download $1"
		download "$1"
		shift
	done
}

play() {
	id=$(date +%T+%N | tr -d '+:')
	url=$(xclip -o -selection clipboard)
	dir=/tmp/youtube/$id

	mkdir -p $dir
	cd $dir

	zenity --info --text="downloading $url" &
	youtube-dl -i $url
	vlc .
}

resume() {
	for file in *
	do
		if echo "$file" | grep -q '.part$'; then
			code=$(echo "$file" | sed -r 's/[.][^-]+$//' | sed -r 's/.*-(\S{8,})$/\1/')
			if ! pgrep -a youtube-dl | grep -q "$code"; then
				download "https://www.youtube.com/watch?v=$code"
			fi
		fi
	done
}

case $1 in
	-p) play $2;;
	--resume) resume;;
	*) toggle $@ ;;
esac


