#!/bin/dash

root=/tmp/suite
local=$root/local
script=$root/jumpu

[ -d $root ] && rm -rf $root
mkdir -p $root

sed '/^## subs ##/,$d' jump-u > $script
sed -n '/^sub/,/^}/p' ~/Development/git/installer/includes/q/jump.pl >> $script
sed '0,/^## subs ##/d' jump-u >> $script

[ -d $local ] || mkdir $local
cd $local
chmod +x $script
$script


